#!/bin/bash

#-------------------------- Settings --------------------------------

# PROJECT_ROOT is passed from fin.
# The following variables are configured in the '.env' file: DOCROOT, VIRTUAL_HOST.

SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SRC_PATH="${PROJECT_ROOT}/src"
THEMES_PATH="$SRC_PATH/themes"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"
VENDOR_PATH="${PROJECT_ROOT}/vendor"
CONFIG_PATH="${PROJECT_ROOT}/config"


#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

#-------------------------- END: Helper functions --------------------------------

cd $PROJECT_ROOT
PWD

echo
echo -n "Which theme do you want to install patternlab? "
read name

THEME_PATH="$THEMES_PATH/$name"
PATTERNLAB_PATH="$THEME_PATH/patternlab"

if [ ! -d "$THEME_PATH" ]; then
   echo "theme does not exist, quitting"
   exit 1
fi

cd $THEME_PATH

echo ""
echo "Installing to $THEME_PATH/patternlab"
echo ""
echo-yellow "You will be asked some questions upon install, the answers are important so pay attention."
echo "Question: No composer.json in current directory, do you want to use the one at <project root>"
echo "Answer: n"
echo "Next three questions: the path <some path> already exists..."
echo "Answer: r"
echo "Quesetion: choose a starterkit"
echo "Answer: 2: pattern-lab/starterkit-twig-drupal-minimal"
echo "Question: a starterkit is already installed. merge the new files with it or replace it?"
echo "Answer: M"
echo ""

composer create-project pattern-lab/edition-drupal-standard patternlab

sed -i '.bak' "s/twigAutoescape: html/twigAutoescape: false/g" patternlab/config/config.yml
echo-green "Set autoescape to false in patternlab/config/config.yml saved backup to patternlab/config/config.yml.bak"
echo ""
sed -i '.bak' "s:../../css/style.css:../../../../css/style.css:g" patternlab/source/_meta/_00-head.twig
echo-green "Set patternlab css path to use theme css in patternlab/source/_meta/_00-head.twig saved backup to patternlab/source/_meta/_00-head.twig.bak"
echo ""

fin exec php patternlab/core/console --generate

echo ""
cd templates
ln -s ../patternlab/source/_patterns/ patterns
echo-green "Linked patternlab _patterns dir to theme/templates/patterns"
echo ""

echo "Install done, some helpful patternlab commands:"
echo ""
echo "To compile patternlab:"
echo "fin patternlab-generate or fin patternlab-generate themename"
echo ""
echo "To watch patternlab files for changes and compile:"
echo "fin patternlab-watch of fin patternlab-watch themename"
echo ""
echo "To start a server to view patternlab:"
echo "fin exec php core/console --server"
echo "Then open: http://localhost:8080 in your browser."
echo "Or open patternlab/public/index.html"
echo ""
echo "To compile, watch, and run server:"
echo "fin exec composer start"
echo ""


