#!/usr/bin/env bash

## Run Code Sniffer (phpcs) against src/modules
## Usage: fin phpcs
##
## Uses Drupal standards.
##
## Includes extensions: php, module, inc, install, test, profile, theme
## Ignores:   features.*, *.pages*.inc

# Environment variables passed from fin:
#
#   $PROJECT_ROOT - (string) absolute path to NEAREST .docksal folder
#   $VIRTUAL_HOST - (string) ex. projectname.docksal
#   $DOCROOT - name of the docroot folder
#   $DOCKER_RUNNING - (string) "true" or "false"

fin run phpcs \
  --standard=Drupal -n \
  --extensions="php,module,inc,install,test,profile,theme" \
  --ignore="*.features.*,*.pages*.inc" \
  src/modules
