#!/bin/bash

## Watches custom themes for changes and recompiles
##
## Usage: fin theme-watch [themename]
##
## Accepts parameters, use 'theme-watch theme' for spcific theme.
## Use w/ no parameters to compile first/only theme in themes dir.

SRC_PATH="${PROJECT_ROOT}/src"
THEMES_PATH="${SRC_PATH}/themes"

cd $THEMES_PATH

# Check for parameters.
if [ $# -eq 0 ]; then
    #If no params compile first theme.
    cd */
    echo -n "watching "
    PWD
    fin exec bundle exec compass watch --poll
else
    #If param, compile only that theme.
    if [ ! -d $1 ]; then
        echo "Directory $1 does not exist, exiting"
        exit 1
    fi
    cd $1
    echo -n "watching "
    PWD
    fin exec bundle exec compass watch --poll
fi
